Fixed the comment adding
Space2Study-UA-1125/backEnd pull request #49
Opened 2024-02-09 10:11 UTC by holus-bolus

2024-02-09 10:19 UTC, Wiret02 approved these changes

2024-02-09 11:59 UTC, iva-stasia approved these changes

2024-02-09 13:52 UTC, iaremchuk approved these changes

2024-02-11 12:12 UTC, VictoriaRodik approved these changes

2024-02-12 14:36 UTC, holus-bolus commented
The code for the services/comments has been changed. The addComments function has been overwritten
![image](https://github.com/Space2Study-UA-1125/backEnd/assets/93076661/e4ef6ac6-5665-4800-86b1-d5d00bcfde0b)


We descturcturize the response from the user and get the according fields. then we look for this user in the database. At last we create a comment.





the comment schema has been changed as well
![image](https://github.com/Space2Study-UA-1125/backEnd/assets/93076661/33dfe60d-a64f-4ced-9ace-582086a2b50d)


instead of just adding the author we get the user type from the scema.

2024-02-14 07:41 UTC, vlad-khrychov requested changes
So, now do we save in DB duplicated information? I think you should change not post endpoint but get endpoint where we obtain comments. In this case from DB you will obtain author id, then using it obtain info about author, then merge all necessary info in response body and after that send response to client.

Also in this PR a lot of additional changes (LICENSE, README). Delete them from this PR. If you want update project documentation it must be separate PR.

2024-02-14 07:41 UTC, vlad-khrychov commented on LICENSE
> +>>>>>>> 6e233d92b9ccda0646f6abfbf6806d082da02b31
resolve conflict

2024-02-14 07:41 UTC, vlad-khrychov commented on README.md
> +=======
Also conflict

2024-02-14 07:41 UTC, vlad-khrychov commented on utils/cooperations/coopsAggregateOptions.js
> +  console.log('User Params:', params)
Delete `console.log`-s

2024-02-14 11:20 UTC, closed without merging

2024-02-14 11:32 UTC, holus-bolus commented
@vlad-khrychov I corrected the code, but I can't reopen the pull request. It says that it has no history with the develop and main

2024-02-14 11:38 UTC, vlad-khrychov commented
> @vlad-khrychov I corrected the code, but I can't reopen the pull request. It says that it has no history with the develop and main

@holus-bolus  open a new PR with your current changes.

2024-02-19 06:30 UTC, holus-bolus commented
> > @vlad-khrychov I corrected the code, but I can't reopen the pull request. It says that it has no history with the develop and main
> 
> @holus-bolus open a new PR with your current changes.
@vlad-khrychov , it's closed and doesn't allow me to open a PR to the closed issue